config/routes.rb
Rails.application.routes.draw do

  #get 'comments/index'
  root "homes#index"
  devise_for :users
  #delete "/users/id/posts", to: "posts#destroy"
  resources :users do
    resources :posts do
     resources :likes 
      resources :comments 
     
    end
  end
  # devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  

  #  scope '(:locale)' do
  #   # We define here a route inside the locale thats just saves the current locale in the session
  #   get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

  #   devise_for :users, skip: :omniauth_callbacks, controllers: { passwords: 'passwords', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  # end
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :likes, dependent: :destroy

          # for Google OmniAuth
  #:omniauthable, omniauth_providers: [:google_oauth2]
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    #debugger
     #@comments=Comment.all
     @comments = Comment.all.where(post_id: params[:post_id]) # comments for particullar post 
     @post = Post.find(params[:post_id]) #FIND CURRENT POST
    
     @comment = Comment.new
  end

 
  # def new
  #   @comment = Comment.new
  # end

  def show
    #debugger
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find( params[:id])
    

  end

 
 def create
   #debugger
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
    @comment = Comment.new #create new object for comment 
    @comments = @post.comments #particullar show comments on post 
    respond_to do |format|
      format.js 
    end
    # if request.format.symbol != :js
    #   redirect_to root_path
    # end
    #@comment.save
    # redirect_to user_post_comments_path
  end

  def destroy
    @post = Post.find params[:post_id]
    @comment = @post.comments.find params[:id]
    @comment.destroy
    redirect_to user_post_comments_path
  end

  private
  def comment_params
    params.require(:comment).permit(:comentext, :body)
  end
end
 

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
   @posts=Post.all
   
  end
  def new
   
  end
end


 

app/controllers/likes_controller.rb
class LikesController < ApplicationController
   #before_action :find_post
  def create
    #debugger
    if already_liked?
       flash[:notice] = "You can't like more than once"
    else
      @post= Post.find(params[:post_id])
      @like= @post.likes.create(user_id: current_user.id)
    #@post.likes.create(user_id: current_user.id)
  end
    redirect_to root_path
  end

  def destroy
    
    if !(already_liked?)
    flash[:notice] = "Cannot unlike"
  else
    #debugger
      @post= Post.find(params[:post_id])
      @like= @post.likes.find_by(user_id: current_user.id)
      @like.destroy
  end
    redirect_to root_path
     
  end

  private
    def already_liked?
     Like.where(user_id: current_user.id, post_id:params[:post_id]).exists?
   
  end
end


 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
  def index
	  @posts=Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    #@post= Post.new
  end
 	
  def create
     debugger
   
     @post = Post.new
     @post.user_id =params[:user_id]
     @post.title = params[:title]
     @post.desc = params[:desc]
     @post.save
     respond_to do |format|
       format.js 
     end
      @posts=Post.all
     
     # redirect_to root_path
 end
 def destroy
    #debugger

    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path, status: :see_other
  end
 
  # private
  #  def post_params
  #  	  params.require(:post).permit(:title)
  #   end 
end


 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_new.html.erb
<h2>Add comment:</h2>
<%= form_with model: @comment, url: user_post_comments_path, id: "myForm" , method: :post do |form| %>
  <p>
    <%= form.label :comentext %><br>
    <%= form.text_field :comentext %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>

 
  

  
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/_showcomment.html.erb
<h3> <strong><%= current_user.email %></strong></h3>
 
  <h2>post name: <%= @post.title %></h2>
 
 <h3>comments on post </h3>
<table border="1">
  <thead>
    <tr>
      <th>commenter Email</th>
      <th>comment</th>
       <th>body</th>
       <th>delete comment</th>

    </tr>
  </thead>

  <tbody >
    <% @comments.each do |comment| %>
     <%# if post.user == current_user %>
          <tr>

            <td><%= comment.user.email %></td>
            <td><%= comment.comentext %></td>
            <td><%= comment.body %></td>
           <% if comment.user == current_user %>
           <%# debugger %>
           <td><%= link_to "Delete",  user_post_comment_path(:id,comment.post, comment),:remote => true , method: :delete %></td>
           <% end %>
         </tr>
    <% end %>
  </tbody>
</table>
<%#= render "new", local: {comments: @comment} %>
<%#= link_to "Back" , root_path %>

app/views/comments/create.js.erb
$("#showcomment").html("<%= j render :partial => 'showcomment', :locals => { comment: @comments } %>");
$("#myForm")[0].reset();
$("#myForm").find("input[type= submit]")[0].disabled = false;
// $("#commet_form").html("<%= j render "new", locals: {comments: @comment} %>"); 

app/views/comments/index.html.erb
<!-- 
<h3> <strong><%#= current_user.email %></strong></h3>
 
  <h2>post name: <%#= @post.title %></h2>
 
 <h3>comments on post </h3>
<table border="1">
  <thead>
    <tr>
      <th>commenter Email</th>
      <th>comment</th>
       <th>delete comment</th>

    </tr>
  </thead>

  <tbody id= "myComments">
    <%# @comments.each do |comment| %>
     <%# if post.user == current_user %>
          <tr>

            <td><%#= comment.user.email %></td>
            <td><%#= comment.comentext %></td>
           <%# if comment.user == current_user %>
           <%# debugger %>
           <td><%#= link_to "Delete",  user_post_comment_path(:id,comment.post, comment), method: :delete %></td>
           <%# end %>
         </tr>
    <%# end %>
  </tbody>
</table>
!--->
<div id="showcomment">
  <%= render "showcomment", local: {comments: @comment} %>
</div>
<div id="commet_form"> 
  <%= render "new", local: {comments: @comment} %>
</div>
<%= link_to "Back" , root_path %>



<script>
  //debugger
  $("#myForm").submit(function(e) {
    e.preventDefault(); //stop html create request 
    var comment = $("#comment_comentext").val();

    $.ajax({
      url: "/users/id/posts/<%= @post.id %>/comments",
      method: 'post',
      data: {comment: {comentext: comment} }
    });

  });
</script>

app/views/homes/index.html.erb
<h1 >Home page</h1>
 <strong><%= current_user.email %></strong>.

<% if user_signed_in? %>
	<%= link_to "Edit", edit_user_registration_path %><br>
	<%= button_to "logout", destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to "Signup", new_user_registration_path %>
	<%= link_to "login", user_session_path %>
<% end %>

<%= link_to "Create post", new_user_post_path(current_user) %>

<%= link_to "Show Post",  user_posts_path(current_user) %>
<%#= render "posts/new" %>

<center>                       
  <h1>Posts</h1>
<table border="1">
  <thead>
    <tr>
    	<th>Poster Email</th>
      <th>post</th>
      <th>comment</th>
      <th>show comments</th>
      <th>likes</th>

    </tr>
  </thead>

  <tbody  class="p-3 mb-2 bg-dark text-white">
    <% @posts.each do |post| %>
      <tr>
      	<td><%= post.user.email %>
        <td><%= post.title %></td>
        <td><%=link_to "create comment", user_post_comments_path(current_user, post.id) %></td>
        <td><%=link_to "show comments", user_post_comments_path(:id,current_user,post_id: post.id) %></td>
         
         <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
         <% if pre_like %>
            <td><%= button_to 'Unlike', user_post_like_path(:id,user_id:current_user.id,post_id:post.id),remote:true, method: :delete,class: "btn btn-outline-danger" %></td>
          <% else %>
            <td><%= button_to 'Like', user_post_likes_path(:id,current_user: current_user.id,post_id: post.id), remote:true, method: :post,class: "btn btn-outline-success" %></td>
         <% end %>
        <td><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" ></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   
  <body>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/_showpost.html.erb
  <center>
  <h1> <strong><%= current_user.email %></strong><br> Posts </h1>
  
<table border="1">
  <thead>
    <tr>
      <th>Poster Email</th>
      <th>post</th>
      <th>Body</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
     <% if post.user == current_user %>
          <tr>
            <td><%= post.user.email %></td>
            <td><%= post.title %></td>
            <td><%= post.desc %></td>
            <th><%=link_to "Delete", user_post_path(current_user, post),:remote => true, method: :delete %></td>
            
         </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= link_to "Back" , root_path %>

app/views/posts/create.js.erb
<%# debugger  %>
$("#showpost").html("<%= j render :partial => 'showpost', :locals => { post: @posts } %>");
$("#MyForm")[0].reset();

app/views/posts/index.html.erb
<div id="showpost" ><%= render "showpost", local: {posts: @post}  %></div>

<%#= render "posts/new" ,local: {posts: @post} %>


 

app/views/posts/new.html.erb
<h2>Add Post:</h2>
<%= form_with model: @user, url:  user_posts_path, id:"MyForm", local:false, method: :post do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
   <p>
    <%= form.label :body  %><br>
    <%= form.text_field :desc %>
  </p>

    <%= form.submit %>
  </p>
<% end %>
<%= link_to "Back",root_path %>